In [ ]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:140px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

In [ ]:
<b><font size="5" color="red">ch10.N차원 배열(Numpy 배열) 다루기(02)</font></b>
- [NumPy](http://www.numpy.org)
- [NumPy Doc](https://numpy.org/doc/)
- 2차원 배열은 행렬개념으로 이해
- numpy 패키지를 이용(C언어로 구현된 고성능 수치계산 패키지)

# 4절 복사와 뷰

## 4.1 할당

In [1]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
b = a

In [3]:
a.shape, a.ndim, id(a), type(a)

((12,), 1, 2498605035376, numpy.ndarray)

In [4]:
b.shape, b.ndim, id(b), type(b)

((12,), 1, 2498605035376, numpy.ndarray)

In [5]:
a is b

True

In [6]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [7]:
np.all(a==b)

True

In [8]:
b.shape = (3,4)

In [9]:
a.shape, b.ndim, id(a), type(a)

((3, 4), 2, 2498605035376, numpy.ndarray)

In [11]:
b.shape, a.ndim, id(a), type(a)

((3, 4), 2, 2498605035376, numpy.ndarray)

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 4.2 얖은 복사 : 뷰(view)

In [17]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
c = a.view()        # 얕은 복사
print(id(a), id(c))

2498639056592 2498639058416


In [23]:
c == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
c.shape = (2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
c[1, ::2] = [9,9,9]
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 9,  9,  9, 11]])

## 4.3 깊은 복사

In [35]:
a = np.array([[5, 5, 15, 0],
             [60, 6, 16, 1],
             [20, 5, 14, 0]])
a

array([[ 5,  5, 15,  0],
       [60,  6, 16,  1],
       [20,  5, 14,  0]])

In [34]:
X = a[:, :-1]
X

array([[0, 1, 2],
       [4, 5, 9],
       [9, 9, 9]])

In [40]:
X[:, 0]= -9
X

array([[-9,  1,  2],
       [-9,  5,  9],
       [-9,  9,  9]])

In [38]:
a

array([[ 5,  5, 15,  0],
       [60,  6, 16,  1],
       [20,  5, 14,  0]])